//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokerBaseEntity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TournamentPlayer
    {
        public int PlayerId { get; set; }
        public int TournamentId { get; set; }
        public int TournamentPlayerId { get; set; }
        public Nullable<int> Place { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual Tournament Tournament { get; set; }
    }
}
